default_profile: native_codex

profiles:
  native_codex:
    type: native
    model: gpt-5.4
  litellm_deepseek_flash:
    model: deepseek-v4-flash
    api_base: http://8.137.196.46/v1
    api_key_env: LITELLM_API_KEY
  litellm_deepseek_pro:
    model: deepseek-v4-pro
    api_base: http://8.137.196.46/v1
    api_key_env: LITELLM_API_KEY
  litellm_minimax:
    model: MiniMax-M3
    api_base: http://8.137.196.46/v1
    api_key_env: LITELLM_API_KEY
    agent_models:
      claude: sonnet
      codebuddy: custom-local:MiniMax-M3
      openclaw: main
  litellm_opencode_go:
    model: opencode-go/minimax-m3
    api_base: http://8.137.196.46/v1
    api_key_env: LITELLM_API_KEY
    agent_models:
      claude: sonnet
      codebuddy: custom-local:MiniMax-M3
      openclaw: main
  litellm_opencode_go_minimax_2_7:
    model: opencode-go/minimax-m2.7
    api_base: http://8.137.196.46/v1
    api_key_env: LITELLM_API_KEY
    agent_models:
      claude: sonnet
      codebuddy: custom-local:MiniMax-M2.7
      openclaw: main
  litellm_opencode_go_grok:
    model: opencode-go/grok-4.6
    api_base: http://8.137.196.46/v1
    api_key_env: LITELLM_API_KEY
  litellm_opencode_go_chat:
    model: opencode-go/longcat-2.0
    api_base: http://8.137.196.46/v1
    api_key_env: LITELLM_API_KEY
